src/ffs/ffs.ts
src/ipfs/basic.ts
src/ipfs/types.ts
src/user/index.ts

Developers want to get content by username not by CID
Use ipfs for dns lookup & add static method to `FileSystem` for loading an ffs by username

Dns lookup & get ffs for user

---

package.json
src/common/type-checks.ts
src/fs/normalizer/header.ts
src/ipfs/encoded.ts
src/ipfs/types.ts
yarn.lock

The type conversion of blobs -> buffers got lost in the big header PR
- re-add that type conversion
- better types on `ipfs.encoded.add`

Blobs -> buffers

---

README.md
src/fs/filesystem.ts
src/misc/dns.ts
src/user/identity.ts
src/user/types.ts

- Added correct links for Travis & Code Climate
- Fixed some linting errors that caused build to fail

Travis & Code Climate

---

src/common/util.ts
src/fs/filesystem.ts
src/fs/header.ts
src/fs/link.ts
src/fs/normalizer/basic.ts
src/fs/normalizer/index.ts
src/fs/normalizer/versions/v0_0_0.ts
src/fs/normalizer/versions/v1_0_0.ts
src/fs/operations.ts
src/fs/private/file.ts
src/fs/private/tree.ts
src/fs/public/file.ts
src/fs/public/tree.ts
src/fs/semver.ts
src/fs/types.ts
src/fs/types/check.ts

Refactor cache implementation to cut down on duplicated info

Cache refactor

---

package.json
src/ipfs/config.ts

Improve discoverability of other nodes by using a signaling server

---

CHANGELOG.md
package.json
src/apps.ts

Added proofs to JWT for app routes. See  #104

Added proofs to jwt for app routes

---

CHANGELOG.md
package.json
src/ucan.ts

UCAN expiration timestamp should not exceed the proof's expiration timestamp

---

CHANGELOG.md
package.json
src/data-root.ts
src/ipfs/config.ts
src/keystore/config.ts
src/lobby/index.ts

Fixes #135 & #137 
Also adds a version of `swarm.connect` with retry, in an attempt to fix #129
And removes `yarn` as a dependency (but makes it a devDependency)

Fixing things

---

README.md

I don’t think there is a docs folder anymore?

Remove link to docs

---

src/auth.ts
src/lobby/index.ts

This is for the dashboard.
Not sure whether `auth.ts` is the right file to put this :/ Help! :smile:

Add resend verification email function

---

src/apps.ts
src/data-root.ts
src/fs/filesystem.ts
src/keystore/config.ts
src/lobby/index.ts
src/ucan.ts
tests/ucan/ucan.test.ts

- backport better ucan header / payload types
- alter encode/decode & signing
- add `ucan.isValid`  and update test

backport changes from #139 for current spec

---

CHANGELOG.md
README.md
package.json
src/apps/index.ts
src/auth.ts
src/common/identifiers.ts
src/common/index.ts
src/data-root.ts
src/filesystem.ts
src/fs/filesystem.ts
src/fs/path.ts
src/fs/root/tree.ts
src/fs/types.ts
src/fs/v1/PrivateFile.ts
src/fs/v1/PrivateTree.ts
src/index.ts
src/keystore/basic.ts
src/lobby/index.ts
src/lobby/username.test.ts
src/lobby/username.ts
src/ucan.ts
src/ucan/internal.ts
src/ucan/permissions.ts
tests/fs/concurrency.test.ts
tests/fs/tree.test.ts

Depends on https://github.com/fission-suite/auth-lobby/pull/50

Leverage multiple read keys and bare name filters given by the lobby

---

src/apps/index.ts

I've changed the apps API after some dogfooding via implementing the dashboard.

improved apps API

---

package.json
src/fs/protocol/private/mmpt.test.ts
src/fs/protocol/private/mmpt.ts
yarn.lock

Note: This test is random. It doesn't _always_ fail. From 1000 added hashes, sometimes it's missing 2, sometimes ~35, sometimes 0. If you want to reproduce, **rerun the test multiple times**
Also, sorry for pulling in the IPFS dependency (only as `devDependency` though). Should I try to get the test running in puppeteer or should we do more of these node-based tests? Especially in the future, given Daniel's work on DI and Brian's work on running tests in node.

Test the MMPT on race conditions

---

src/fs/root/tree.ts

Might be some other inconsistencies.

Fix root path in RootTree.empty

---

tsconfig.json

Set ES2015 as target in tsconfig

---

nix/sources.json
shell.nix
src/fs/data/private/spiralratchet.test.ts
src/fs/data/private/spiralratchet.ts

A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
For more information, see the `CONTRIBUTING` guide.
Explain the **motivation** for making this change. What existing problem does the pull request solve?
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Fixes #

Secure math for spiral ratchet

---

CHANGELOG.md
package.json
src/apps/index.ts
src/common/api.ts
src/common/version.ts
src/data-root.ts
src/lobby/index.ts
src/lobby/username.ts
src/setup/internal.ts

This is the first step for "App Owned Logins" - allowing the rest API endpoint to be configurable. 
Fixes #317

make rest endpoint configurable

---

CHANGELOG.md
src/filesystem.ts
src/fs/root/tree.ts

Fixes #323 
Can you try this one out @bgins? :pray:

Assume filesystem version 1.0.0 if version link is missing

---

src/auth/channel.ts

This PR fixes the following **issues**
Sometimes the root DID lookup fails. The root cause is not known yet but this PR implements a fix for it. We simply retry when the first attempt fails. 
```bash
yarn test
```
Fixes #338

Root DID Lookup Retry

---

package.json
yarn.lock

I noticed there were some vulnerabilities reported by dependabot, this should resolve them. r- @bgins

updated depedencies, some vulnerabilities

---

src/ipfs/node/repo.ts

Add raw and cbor codecs to the lookup in ipfs repo

---

src/index.ts

This checks if the context and browser are supported before initialising the default components, instead of after. Certain components use indexedDB, so we want the check to be done before that code is called. It only checks when calling `.program()`, not `.assemble()` (see code docs for more info). `.isSupported()` is also exported.

Perform browser checks before components init

---

src/components/manners/implementation/base.ts
src/fs/data.ts

Forgot an `await` and removed an unnecessary `publish`

Minor file system fixes

---

CHANGELOG.md
README.md
src/fs/data.ts
src/index.ts
tests/fs/data.node.test.ts

Add file system data functions as shorthand methods

---

CHANGELOG.md
src/index.ts

Improve Program type

---

CHANGELOG.md
package-lock.json
package.json
src/common/version.ts
src/fs/filesystem.ts
src/fs/types.ts
tests/fs/api.private.node.test.ts
tests/fs/api.public.node.test.ts

Allow symlinks to other file systems to be created

---

README.md

Fixes broken link to docs on "sharing private data"

Fix link on sharing private data in README

---

README.md

Add install instructions to the readme.

Add install instructions to the readme.

---

src/fs/v3/DepotBlockStore.ts

Code comments seem to mismatch functions

fix: mismatching comments for DepotBlockStore
