package.json, src/ffs/private/tree.ts, src/ffs/public/tree.ts, src/ffs/public/util.ts, src/ffs/types.ts
`getRecurse` base cause is throwing an error when accessing an empty path instead of returning the parent tree
Change `getRecurse` to return `null` instead, use the `NonEmptyPath` data type, and leave error handling to the caller
=> Fix get recursion for empty paths

package.json, src/fs/operations.ts, src/fs/private/tree.ts, src/fs/public/tree.ts, src/fs/types/check.ts, src/fs/util.ts, src/ipfs/encoded.ts
Circular dependency arising from `common` refactor
- fix imports to eliminate circular dependency
- quick reorg of some functions. including renaming `fs/utils` to `fs/operations`
=> Fix circular dependency

src/fs/filesystem.ts, src/fs/normalizer/header.ts, src/fs/public/tree.ts
Currently we have the following structure:
```shell
/index/public
/index/public/dir/index/item/index
/index/private
```
This PR adds:
```shell
/index/pretty
/index/pretty/dir/item
```
It does this by having a copy of the public tree, which always has the version `v0`.
---
I did a quick test, which you can find here:
https://icidasset-test-3.fission.name/index/pretty/Testing%20Public
=> Add a pretty tree alongside the public tree

src/common/index.ts, src/common/type-checks.ts, src/common/types.ts, src/fs/normalizer/basic.ts, src/fs/normalizer/header.ts, src/fs/normalizer/index.ts, src/fs/normalizer/versions/v0_0_0.ts, src/fs/normalizer/versions/v1_0_0.ts, src/fs/public/file.ts, src/fs/public/tree.ts, src/fs/types.ts, src/ipfs/encoded.ts
A lot of our code had an optional param `key?: string` which would optionally encrypt data before uploading. This could cause issues of unwittingly not passing the key variable along with no warning from the compiler.
Added a `Maybe` type so that this is explicit
_haskell intensifies_
=> added maybe type

package.json, src/fs/filesystem.ts, src/fs/types.ts
No way to move files around within filesystem
Add `mv` method to FileSystem
Note that the unix `mv` command actually has several implementations where the second parameter can either represent a destination folder or the name of the actual destination file.
I only included the second implementation here for simplicity's sake.
so for instance if you want to move `private/photos/headshot.jpg` to `public.photos/headshot.jpg`, you wil do
`fs.mv('private/photos/headshot.jpg', public/photos/headshot.jpg` 
_NOT_
`fs.mv('private/photos/headshot.jpg', public/photos')`
=> Add mv method to FileSystem

README.md, package.json, src/@types/index.d.ts, src/data-root.ts, src/dns/index.ts, src/index.ts, src/ipfs/basic.ts, src/ipfs/config.ts, src/ipfs/index.ts, src/ipfs/types.ts, src/setup.ts, src/setup/internal.ts, yarn.lock
Changes:
- Adds info about authentication and data-root stuff to the readme
- Adds support for js-ipfs v0.48 (filesystem change, see `basic.add`)
- Adds `setup` module to allow customisation and additional options (eg. for js-ipfs)
- Data root now uses the `username.files.${users_toplevel_domain}` domain
- Fixes repo link in `package.json`
- Set js-ipfs version to `0.48` instead of `latest` (get-ipfs default)
- Sorts TXT records by their prefix if prefix is present and then joins them together (see function docs for details)
Fixes #60, #62, #63 and #65
=> TXT DID Records, data root changes and js-ipfs 0.48 support

package.json, src/common/crypto.ts, src/core/did.ts, src/fs/bare/tree.ts, src/fs/base/tree.ts, src/fs/filesystem.ts, src/fs/network/header.ts, src/fs/path.ts, src/fs/pins.ts, src/fs/types.ts, src/fs/v1/PublicTree.ts
- Our server needs to pin a user's private file tree, but it can't crawl it because it's..... private
- right now this is accomplished with loose pins which are cumbersome to deal with
- when a subtree is shared with a user, they should retain access to it even if the CID changes. So they need to be able to look up the current CID of the tree by using a given filepath
- Add a single-layer /pins node off of the FS root
- That node will include a list of all nodes in the private file system. The names of the nodes will be a hash of the name plus their DID which acts as a salt: sha(filename + did)
An example snippet of this:
{ name: sha("private/index/file" + did), cid: "Qm123..." },
{ name: sha("private/index/file/index" + did), cid: "Qm456..." },
{ name: sha("private/index/file/isFile" + …
=> Pins for private file tree

package.json, src/fs/types/check.ts
`isPinMap` runtime type check was not doing a proper check, causing header values to fail to be parsed
Fix type check
=> Pinlist hotfix

CHANGELOG.md, README.md, src/common/debug.ts, src/filesystem.ts, src/fs/filesystem.ts, src/setup.ts, src/setup/internal.ts
Changes:
- Fixed write, is an alias for `add` now, as you suggested.
- Improved throttle, doesn't update the data root with the first cid, but waits first.
- Added a "debug mode" via the setup module, which does various `console.log`s. So we can debug the loading of the file system, among other things.
=> Remove write and improve filesystem loading

CHANGELOG.md, README.md, package.json, src/apps.ts, src/index.ts
App changes for #80.
Added
- index
- create
- delete
To note - Despite the API docs having a query param for creating a specific subdomain, I was having trouble getting it to work locally. See optional input param ->
https://github.com/fission-suite/webnative/compare/master...nathanmalishev:feature/api-endpoints?expand=1#diff-f184519d3b4aa08687df8c56a277205aR44
Should I remove it from the optional param?
=> Apps changes

package.json, rollup.config.ts, yarn.lock
`travis-deploy-once` has `dot-prop` as a dependency which has a security vulnerability. We're not actually using `travis-deploy-once` & the package is actually deprecated at this point
Remove `travis-deploy-once`
=> Remove travis-deploy-once

package.json, src/fs/filesystem.ts
When loading WNFS from a CID & a private branch does not exist, it will create a new private MMPT, but will attempt to load the root of the private tree as if it exists, causing an error
Create a new MMPT & create a new private tree root
=> bugfix: if no private tree when loading WNFS, create new

src/ipfs/config.ts
Content routing is no good in the browser
Delegate content/peer routing to our remote node
This delegation occurs of https, so we direct it to the http public gateway instead of the websockets p2p port
=> Add IPFS Delegate Node

src/common/async.ts, src/dns/index.ts
Cloudflare can intermittently be slow & unresponsive
When doing DNS lookups, race Google & Cloudflare DNS-over-HTTPS and return the first to finish
=> Race google & cloudflare lookups

CHANGELOG.md, README.md, package.json, src/auth.ts, src/filesystem.ts, src/fs/filesystem.ts, src/index.ts, src/ucan/internal.ts, src/ucan/permissions.ts
I hinted at this in the API blog post I made: https://talk.fission.codes/t/user-facing-api/1013
I think that the return value for `initialize` can be simplified some.
I removed `prerequisites` & changed `scenario` to be an `enum` on `State`
Let me know what you think! I'm not married to this by any means, and you've been using this code in practice way more than I have, so I trust your judgement on it!
=> Reorganize initialise return value

package.json, src/index.ts, src/keystore/config.ts, yarn.lock
Read key is being sent plaintext in query params when redirecting back to app
- Encrypt with the app's exchange key & decrypt in the app
- `keystore.decrypt` was broken, so we need to upgrade `keystore-idb`
Relies on https://github.com/fission-suite/auth-lobby/pull/19
=> Decrypt read key from auth lobby

src/fs/protocol/basic.ts, src/ipfs/types.ts, src/ipfs/util.ts
`ipfs.ls` does not return size for directories. I could've sworn that this worked in the past :thinking: but it doesn't return size in the in-browser daemon or a local go-ipfs node so this seems intentional
Combine `ipfs.ls` output with `ipfs.dag.get` output to get the entire object that we're looking for
=> Return size on public dirs

package.json, src/fs/bare/tree.ts, src/fs/base/tree.ts, src/fs/filesystem.ts, src/fs/protocol/private/index.ts, src/fs/protocol/private/mmpt.ts, src/fs/types.ts, src/fs/v1/PrivateFile.ts, src/fs/v1/PrivateTree.ts, src/fs/v1/PublicTree.ts
Our IPFS Gateway is not grabbing all of the content needed for a user's FS. This is because file content is not being correctly added to the MMPT on the private side.
- Put file contents in MMPT
- properly revision files & contents in MMPT
Also:
- add `members()` method to MMPT for debugging
- add `localOnly` flag for filesystem for local testing purposes
=> Put files in MMPT & do file revisions properly

package.json, src/data-root.ts
DNS takes a while to propagate, and especially on initial lookups, it can take > 15 min
Hit new server route for a user's DataRoot, if that fails, then go to DNS
=> Hit fission server for dataroot

src/ipfs/basic.ts, src/ipfs/config.ts
Our IPFS browser daemon can become disconnected from the remote node & then end up spinning it's wheels trying to grab content
Reconnect before each operation. This is a _very_ lightweight operation
=> Reconnect before each operation

src/data-root.ts, src/fs/v1/PrivateFile.ts
We initially set a user's data root to a CID representing the empty string (to speed up DNS propagation). However the code expects a user's dataroot to be `null` when a filesystem does not exist. This initially wasn't an issue, because DNS wasn't fast enough to propagate the empty CID. But now that we retrieve DNS directly, we're trying to parse a filesystem object from an empty CID
On DNS lookup, interpret the empty CID as `null`
Also added a debug statement & fixed the wording in an error
=> Treat empty cid as null value

CHANGELOG.md, package.json, src/ipfs/basic.ts, src/ipfs/types.ts
Pinning is recursive by default
Since we pin any resource we `cat`/`ls`, we're downloading the entire FS on initial page load
Change pins to non-recursive, so we only download what's necessary
=> Do not recursively pin CIDs

CHANGELOG.md, package.json, src/ipfs/basic.ts
We're pinning async, so the error isn't being caught
`await` on pin
=> Await on pin to catch error

CHANGELOG.md, package.json, src/fs/filesystem.ts, src/fs/types/check.ts, src/fs/v1/PublicTree.ts
Public write methods aren't getting run on the `pretty` tree. This is because the `PublicTree.instanceOf` method is not formatted correctly.
Update `PublicTree.instanceof` to correctly identify public trees. Also update the user of `info`/`header` to be more consistent
=> Fix type check for public tree

CHANGELOG.md, package.json, src/fs/v1/PublicTree.ts
Updating files on the public tree fails because we incorrectly identity files as directories. This is because files _are_ directories at the protocol level, but _not_ at the platform level 
Check if a given node is a file in the node's skeleton (the platform-level description) instead of the node's links (the protocol level description)
=> Bugfix: Public tree update files

CHANGELOG.md, package.json, src/auth.ts, src/common/cid-log.ts
Wasn't clearing all the data before, which was causing some issues when creating a new account. More specifically, the sdk tried to load a different file system because the CID log was still in the indexeddb. Additionally I cleared the keystore as well, so the user starts with fresh keys.
=> Clear all data when leaving

CHANGELOG.md, package.json, src/common/base64.ts, src/index.ts
I'm making the base64 of the encoded read-key url-safe on the auth lobby side. Now it supports both url-safe and non url-safe base64.
Context: Fixing this https://github.com/fission-suite/auth-lobby/issues/21
=> Support the decoding of the url-safe base64 encoded read-key from the auth lobby

Justfile, package.json, src/fs/bare/file.ts, src/fs/bare/tree.ts, src/fs/base/file.ts, src/fs/base/tree.ts, src/fs/filesystem.ts, src/fs/link.ts, src/fs/path.ts, src/fs/protocol/basic.ts, src/fs/protocol/private/index.ts, src/fs/protocol/private/mmpt.ts, src/fs/protocol/private/namefilter.ts, src/fs/protocol/private/types.ts, src/fs/protocol/public/index.ts, src/fs/protocol/public/types.ts, src/fs/root/tree.ts, src/fs/types.ts, src/fs/types/check.ts, src/fs/v1/PrivateFile.ts, src/fs/v1/PrivateHistory.ts, src/fs/v1/PrivateTree.ts, src/fs/v1/PublicFile.ts, src/fs/v1/PublicHistory.ts, src/fs/v1/PublicTree.ts, src/ipfs/basic.ts, src/ipfs/types.ts
The Filesystem does not allow concurrent operations. Two write operations at the same time will overwrite one another.
- make the MMPT concurrent
- make the filesystem concurrent
- also roll in changes for versioning on the public side (https://github.com/fission-suite/webnative/pull/125) to avoid rebases etc
=> Concurrent FS operations & basic versioning

CHANGELOG.md, README.md, package.json, src/@types/index.d.ts, src/auth.ts, src/common/crypto.ts, src/fs/filesystem.ts, src/ipfs/basic.ts, src/ipfs/config.ts, src/ipfs/types.ts, src/ipfs/util.ts, src/setup.ts, src/setup/internal.ts, tsconfig.json, yarn.lock
Closes  #79
Moves the js-ipfs node to the auth lobby and sets up a tunnel to a shared worker on that lobby, through an iframe. That iframe is inserted automatically when you call `webnative.initialise()`. Additionally this makes webnative work in a web worker.
=> Use a shared worker

CHANGELOG.md, package.json, src/lobby/index.ts, src/lobby/username.test.ts, src/lobby/username.ts
Today, users are restricted to non-underscored usernames and app names (subdomains).
also our regex check isn't properly disallowing bad usernames (worst case our server rejects but would still be nice to give a user a heads up)
- Allow underscores in the validator
- disallow usernames that start with underscores so that we don't have conflicts with _did, _dataroot, _dnslink, etc
- fix regex so it doesn't allow special characters (someone plz double check my regex! it appears to work well, but regex has always been a weak spot for me)
- lowercase usernames before checking against block list
- still allow uppercase because that all gets normalized on the server
=> Fix regex for usernames & allow underscores

package.json, src/common/arrbufs.test.ts, src/common/base64.test.ts, src/common/hex.test.ts, src/common/type-check.test.ts, src/common/util.test.ts, yarn.lock
This PR brings in a unit tests and property checks for modules in `src/common/`. 
A run of the tests with `npm run test:unit` should result in:
=> Add common unit tests and prop checks

src/auth.ts, src/ipfs/config.ts
Lets us optimise for the fast path.
Adds the temporary auth data to the shared worker via ipfs, instead of to the user's filesystem.
=> Notify the lobby we're using a shared worker

README.md, package.json, src/auth.ts, src/ucan/internal.ts, src/ucan/permissions.ts, tests/fs/concurrency.test.ts, tests/fs/tree.test.ts, tests/types/ucan/permissions.test-d.ts, yarn.lock
This replaces
```js
initialise({
permissions: {
fs: {
privatePaths: [ "Music" ],
publicPaths: [ "Mixtapes" ]
}
}
}
```
with
```js
initialise({
permissions: {
fs: {
private: { directories: [ "Music" ], files: [] },
public: { directories: [ "Mixtapes" ], files: [] }
}
}
}
```
Then it passes the paths to the lobby in the following way:
- Directory: `foo/bar/`
- File: `foo/bar`
Also cleans up the way functions, that use permissions, deal with paths.
The SDK and lobby currently assume every filesystem permission is a directory, but we need to support files too.
=> Improve permission path handling

src/data-root.ts, src/fs/filesystem.ts, src/fs/types.ts, src/ucan.ts, src/ucan/internal.ts
The idea here is to follow the convention of the fission server, and that's to never re-encode a UCAN. For example, we ran into issues because of a `prf: null` and `prf: undefined` inconsistency. The reason this was happening is because we decoded UCANs from other sources and then re-encoded them. This PR changes that.
Also fixes a issue with `ucan.encode`, namely that it could return an unexpected Promise.
=> Keep existing UCANs in their original state

package.json, src/common/version.ts, src/index.ts
Depends on https://github.com/fission-suite/auth-lobby/pull/72
Creates a small iframe to exchange the linking secrets with the auth lobby.
The auth lobby can signal that it supports this flow by providing the query parameter `authoised=via-postmessage` after redirecting back from `redirectToLobby`.
=> Implement new flow for exchanging secrets with the auth lobby

src/fs/filesystem.ts, src/fs/protocol/private/index.ts, src/fs/protocol/private/types/check.ts, src/fs/root/tree.ts, src/fs/v1/PrivateFile.ts, src/fs/v1/PrivateTree.ts, src/ucan/internal.ts
The private side of the sdk expects all entry points to be directories. But we can now permission files as entry points
Allow both files & directories as entry points on the private side
=> Load private files in root tree

CHANGELOG.md, package.json, src/crypto/index.ts, src/setup/dependencies.ts, src/storage/index.ts
- merging dependencies is not a deep merge
- `crypto` & `storage` modules get set off the original implementation and not updated on `setDependencies
- deep merge dependencies on set
- make sure `crypto` & `storage` modules use the currently set implementation
=> Fix DI issues

CHANGELOG.md, package.json, src/common/browser.ts, src/crypto/browser.ts
The browser detection was assuming the `window` object which is not available in web/service workers. This PR replaces that with a check for the `location` object, which is both available on main ui thread (window object) and [worker contexts](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope).
Published this as `0.24.1-alpha-2` if you want to test it.
=> Browser detection should include workers

CHANGELOG.md, package.json, src/common/version.ts, tsconfig.json
tsc is outputting built files to `dist/src/` instead of `dist`. This breaks type references such as `types` in `package.json`
This is because some code in `src` (specifically `setup/jest.ts`) references some code in `tests/`
So we exclude `src/setup/jest.ts` in `tsconfig.ts`
=> Fix tsc output

src/index.ts
Related to https://github.com/fission-suite/auth-lobby/pull/76
> This PR fixes/implements the following **bugs/features**
* On secret retrieval during first authentication, webnative will send the app's exchange DID
> Explain the **motivation** for making this change. What existing problem does the pull request solve?
This will fix bugs when multiple apps try to authenticate with the auth lobby at the same time
> Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
I've tested this against a newer auth-lobby at https://philipps-auth-test.fission.app and with https://dashboard-altlobby.fission.app/ built with this branch.
I've also tested https://dashboard-develop.fission.app with the lobby endpoint …
=> Improve the secret exchange flow

src/keystore.ts
Fixes a bug where calling `webnative.crypto.keystore.clear()` wouldn't actually clear the keystore unless you ran some other keystore operation before which would've internally loaded it.
=> Also clear the keystore when it wasn't loaded before

.github/workflows/changelog.yml, package.json, src/@types/index.d.ts, src/did/transformers.ts, yarn.lock
This PR replaces usage of `base58-universal` with `uint8arrays`
> Explain the **motivation** for making this change. What existing problem does the pull request solve?
We depend on a *branch* in the `base58-universal` github repository, instead of on the npm package. This means it has to be built by anyone using webnative (if they use webnative as an npm package). This process can be flaky (#260).
Instead, we can depend on `uint8arrays`, which is a dependency of many of *our* dependencies. E.g. [js-ipfs-core depends on it](https://github.com/ipfs/js-ipfs/blob/dc041aa3de789290bfc5c1c0b8c2878d8c79186a/packages/ipfs-core/package.json#L123).
It makes sense to go with ecosystem momentum here.
> Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / …
=> Replace base58-universal dependency with uint8arrays (& add changelog checker)

CHANGELOG.md, package.json, scripts/build-minified.js, tests/fixtures/index.html, tests/helpers/page.ts
When we switched to `esbuild`, we dropped UMD support, because it doesn't support that natively. This PR brings it back using esbuild's `banner` and `footer` options.
The motivation for this was that TiddlyWiki uses and expects UMD in the browser.
> Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
There's a [test](https://matheus23.files.fission.name/p/webnative-umd/) running webnative in the browser using the UMD build, it works.
I didn't test TiddlyWiki, yet. I've sent @saqimtiaz a message on discord, so he can give me some feedback.
* Make a release
=> Bring back the umd build

package.json, scripts/TYPEDOC.md, src/fs/base/file.ts, src/fs/protocol/public/index.ts, src/fs/types/check.ts, typedoc.json, yarn.lock
Some typedoc improvements: There's now a root 'readme' for the typedocs, and we're only running typedoc once and configured it slightly differently.
> Explain the **motivation** for making this change. What existing problem does the pull request solve?
Our typedocs previously weren't linked to each other correctly. So e.g. I wouldn't be able to take a look at the `FileContent` type when I was inside the `FileSystem` class. Also there were no links to `FileSystem` form the root of the docs, you'd have to know about `webnative.fission.app/fs`. 
Hm. Ideally I want the docs to be rendered in github actions, but for that I'd need access to the fission account that belongs to `webnative.fission.app` (I think you have that @icidasset?).
=> Typedoc Improvements

src/fs/protocol/private/namefilter.test.ts, tests/fs/api.private.node.test.ts, tests/fs/api.public.node.test.ts
This PR adds an initial set of tests of the namefilter implementation used in the private filesystem.
We run each test 10,000 times because they are fast and they finish before some of our other longer running tests.
The new tests should pass in the GH action and can also be run in isolation with
```
yarn test --grep "filter"
```
All tests should pass.
=> Add namefilter tests

CHANGELOG.md, package.json, src/apps/index.ts
The server format has changed, this PR updates the expected format.
Now returns a list of domains, and also the `insertedAt` and `modifiedAt` ISO8601 timestamps.
Tested with this branch of the dashboard (required a few minor changes):
https://github.com/fission-suite/dashboard/compare/icidasset/app-index?expand=1
=> Fixes #272

CHANGELOG.md, package.json, src/common/version.ts, src/index.ts
This happens to me from time to time when logging in with fission apps:
I identified the cause of this issue to be my "10ten" extension. It would `postMessage` from the `auth.fission.codes` origin with a message like `10ten(X)ping`.
Webnative would think that a message from the auth lobby must be login info and try to parse that as JSON.
I should've really thought of the whole `postMessage` thing like a distributed system. We just don't know anything about the messages we're getting.
So, the assumptions I'm making now is that we won't get more than 9 unrelated messages and we'll the message we care about within 10 seconds.
With the 10ten extension enabled, I don't have any problems logging in anymore.
=> Improve login flow resilience against extensions

nix/sources.json, shell.nix
The nix shell will not build on machines with the `aarch64` architecture. This change lets us override and use `x86_64`.
On an M1 mac, set up the nix with
```
nix-shell --arg rosetta true
```
Note that your `/etc/nix/nix.conf` will need to contain this line:
```
extra-platforms = x86_64-darwin
```
=> Add rosetta nix override

CHANGELOG.md, package.json, src/common/version.ts, src/crypto/browser.ts, src/setup/node.ts, tsconfig.json, yarn.lock
Explain the **motivation** for making this change. What existing problem does the pull request solve?
The `noble-ed25519` library uses big integer literals which only work in `es2020` or newer environments. This PR replaces `noble-ed25519` with `tweetnacl` to support older environments. See #276 for more details.
We use the [verify](https://github.com/paulmillr/noble-ed25519#verifysignature-hash-publickey) method from `noble-ed25519`. This PR replaces it with [sign.detached.verify](https://github.com/dchest/tweetnacl-js#naclsigndetachedverifymessage-signature-publickey) from `tweetnacl`. 
The function signatures are nearly the same. `noble-ed25519` permits more types and `tweetnacl` requires `Uint8Array`s. This is enforced here: …
=> Replace noble-ed25519 with tweetnacl

.github/workflows/docs.yaml, fission.yaml
This'll deploy the docs to https://webnative.fission.app when a non-alpha release is made.
Info about 'releases' glob pattern:
https://docs.github.com/en/enterprise-server@2.22/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns
Closes #175
=> Auto-publish docs on release

CHANGELOG.md, package.json, src/common/version.ts, src/index.ts, yarn.lock
Allows webnative to be used in more environments.
Main action is a version bump of one-webcrypto to 1.0.3 and keystore-idb to 0.15.4 (which again is only due to a version bump of one-webcrypto).
Discussed in #318
=> Bump one-webcrypto to 1.0.3 and keystore-idb to 0.15.4

CHANGELOG.md, package.json, src/common/type-checks.ts, src/common/version.ts, src/filesystem.ts, src/fs/bare/tree.ts, src/fs/base/file.ts, src/fs/base/tree.ts, src/fs/filesystem.ts, src/fs/link.ts, src/fs/protocol/basic.ts, src/fs/protocol/private/index.ts, src/fs/protocol/private/types.ts, src/fs/protocol/private/types/check.ts, src/fs/protocol/public/index.ts, src/fs/protocol/public/skeleton.ts, src/fs/protocol/public/types.ts, src/fs/root/tree.ts, src/fs/types.ts, src/fs/types/check.ts, src/fs/v1/PrivateFile.ts, src/fs/v1/PrivateTree.ts, src/fs/v1/PublicTree.ts, src/path.ts, tests/fs/api.private.node.test.ts, tests/fs/api.public.node.test.ts, tests/fs/integration.node.test.ts
Symbolic links are in the following format:
```javascript
// Public soft link
{
ipns: "icidasset.files.fission.name/public/path/example.file",
name: "example.file"
}
// Private soft link
{
ipns: "icidasset.files.fission.name",
name: "example.file",
key: aes_key,
privateName: "..."
}
```
The `name` is name of your symbolic link, and the other properties involve the original file or directory. When a soft link is resolved, webnative will lookup the DNSLink, load the part we need of the other person's filesystem and then get the file or directory (read only).
This PR implements the following functions:
```javascript
// Top level soft link creation
fs.symlink({ at: DirectoryPath, referringTo: DistinctivePath, name: string, username?: string }): Promise<this>
// Lower level soft link creation …
```
=> Add soft links

src/index.ts
Just a console.log that slipped through.
It prints the variable "classifiedInfo", but that's not dangerous. The contents of that variable are encrypted with a non-extractable key.
Still, not necessary to have that printing.
=> Remove debug console.log

package.json, src/common/version.ts, src/filesystem.ts, src/fs/versions.ts, src/setup/internal.ts, tests/fs/versioning.node.test.ts
The `isSmallerThan` function was incorrect. This should fix it.
```js
$ node --experimental-repl-await
Welcome to Node.js v16.9.1.
Type ".help" for more information.
> versions = await import("./lib/fs/versions.js")
> versions.isSmallerThan(versions.fromString("1.0.0"), versions.fromString("1.0.0"))
false
> versions.isSmallerThan(versions.fromString("1.0.0"), versions.fromString("2.0.0"))
true
> versions.isSmallerThan(versions.fromString("1.0.0"), versions.fromString("1.1.0"))
true
> versions.isSmallerThan(versions.fromString("1.0.0"), versions.fromString("1.0.1"))
true
> versions.isSmallerThan(versions.fromString("1.0.1"), versions.fromString("1.0.1"))
false
> versions.isSmallerThan(versions.fromString("0.0.1"), versions.fromString("1.0.1"))
true
> …
```
=> Fix version check

CHANGELOG.md, src/auth/index.ts, src/auth/lobby.ts, src/auth/local.ts, src/index.ts, src/setup/dependencies.ts
This PR introduces dependency injection for initialization and account registration (along with the various username validation features). This allows apps to override these and potentially use alternative authentication backends / mechanisms.
It also introduces a "local" version that allows an app to init/register accounts in a self-contained manner like this:
```js
import { LOCAL_IMPLEMENTATION } from "webnative/auth/local";
setDependencies(LOCAL_IMPLEMENTATION);
wn.initialise({ loadFileSystem: false })
.then((result) => {
const { authenticated, username } = result;
if (authenticated) {
console.log(`Logged in as: ${username}`)
}
})
.catch((e) => console.error(e));
```
Closes #316 
Closes #302
=> App owned logins

package.json, src/common/version.ts, src/fs/base/tree.ts, src/fs/filesystem.ts, src/fs/protocol/private/mmpt.ts
This was causing the "Shared with me" folder not to load on my other devices. Because `.put()` was called multiple times on that folder, causing it to be added multiple times to the MMPT with different CIDs. `.put()` produces different CIDs every time because the AES encryption is done with a random `iv` value, and the MMPT doesn't allow addition of the same key/namefilter multiple times (it will keep the first, original, value).
- Removes multiple `put` calls
- Adds MMPT warning in case this happens elsewhere
=> Don't `put` multiple times and add MMPT warning

package.json, src/auth/linking/consumer.ts, yarn.lock
This PR fixes the following **issues**
Currently pin sampling method has a slight bias towards low numbers (0-5). This PR gets rid of this bias with updated `randomBuf` implementation that takes a max param and uses rejection sampling. 
Making sure existing tests around pin generation still pass. 
```bash
yarn test:prod -g "generates a pin and challenge message"
```
Fixes #359
=> Rejection Sampling in Pin Gen, AWAKE

src/ipfs/basic.ts, tests/fs/share.node.test.ts
`cid`s have been updated to use the multiformat-based CID class but old code still use string encoded formats which leads to vague errors. This PR adds a check that returns a clear error message when a cid parameter isn't an object.
Fixes #345
=> Type-Check CID

src/auth/channel.ts
This PR fixes the following **bug**
PR #367 implements root DID lookup retrying but does not address the initial 2 sec delay from `setInterval` as noted by @icidasset. This PR fixes that.
```sh
yarn test
```
=> Fix Initial Delay in DID lookup

CHANGELOG.md, src/fs/filesystem.ts, yarn.lock
The CIDs from the share links (ie. DAG objects) aren't always strings, as expected before. This PR removes the strict string type check and just checks for existence instead.
=> Fix issue with loading shares

CHANGELOG.md, package.json, src/auth/implementation/base.ts, src/auth/implementation/use-wnfs.ts, src/auth/linking/consumer.test.ts, src/auth/linking/producer.test.ts, src/common/version.ts, src/filesystem.test.ts, src/filesystem.ts, src/index.ts, src/init/types.ts, tests/auth/linking.node.test.ts
This PR makes it possible for apps to create WNFS without visiting the auth lobby.
The features in the PR will only make sense for apps with root authority. We can make these features coherent for linked apps when we implement app-owned app linking. For now, apps that initialize webnative with `permissions` will ignore the `useWnfs` option.
The `useWnfs` option is passed to `webnative.initialize`:
``` typescript
wn.initialise({ useWnfs: true })
.then(async (state: State) => {
switch (state.scenario) {
case wn.Scenario.Continuation:
// state.fs available
case wn.Scenario.NotAuthorised:
// state.fs not available
})
```
We check if the user has a data root in their CID log, on the server, or in DNS. If any of these exist, we load their existing …
=> App owned: Add use WNFS implementation

CHANGELOG.md, src/auth/implementation/base.ts, src/auth/implementation/lobby.ts, src/auth/implementation/types.ts, src/auth/index.ts, src/auth/internal.ts, src/lobby/index.ts
This PR makes the email parameter to the `register` function optional. It goes along with the changes on the server (https://github.com/fission-suite/fission/pull/619) where a user can register with a only a username _or_ a username and email.
Tested by registering a user with and without an email.
Closes #393
=> Update `register` to make email optional

CHANGELOG.md, src/filesystem.ts
The existing `boostrapFileSystem` function will override a user's filesystem with an empty one. This function is dangerous and could use some guard rails.
When the `reset` option is set to `false`, we check if a filesystem exists and throw an exception if so. The `reset` option can be explicitly set to `true` if a filesystem reset is desired. The `reset` option defaults to `false`.
The check for an authed user was needed for checking the filesystem, but is a general improvement because we need a user here.
The change can be tested by calling `bootstrapFileSystem` in an app where a user already has a filesystem. The call should fail, but setting the `reset` option to `true` should succeed and reset the filesystem.
Closes #396
=> Add filesystem reset protection

src/ipfs/node.ts
Peer list values are incompatible with the old format.
=> Use a new storage name for the peer list

CHANGELOG.md, package.json, src/common/version.ts, src/dns/index.ts
This PR fixes the following **bugs**
=> Fix DI `lookupDnsLink` function

CHANGELOG.md, src/ipfs/config.ts, src/ipfs/node.ts
This fixes an issue with certain endpoint configurations and empty peer lists.
Sometimes it was using `/api/vx/ipfs/peers` instead of `/ipfs/peers`, and it didn't work with empty peer lists (or peer lists that didn't have usable peers in it).
Also fixes #416
=> Improve peer list storage

CHANGELOG.md, package.json, scripts/gen-version.js, src/common/version.ts, yarn.lock
We were previously using urls like `https://unpkg.com/wnfs@^0.1.7-alpha5` to fetch the WASM blob.
This is very problematic, since that URL's contents can change when we publish new versions of the `wnfs` npm package.
And we need the `.wasm` file to match *exactly* the version of the JS glue code around it.
So publishing a newer version lead to unpkg redirecting the `0.1.7-alpha5` version to `0.1.7` and breaking:
So, we need to ask unpkg for *exactly* the version we want.
I wrote some code that looks the exact version we resolved wnfs to in the yarn lockfile, and we're using that instead.
=> Fix: Resolve exact wnfs version in unpkg

CHANGELOG.md, package-lock.json, src/components/auth/channel.ts
This PR fixes/implements the following **bugs**
Uncaught exceptions are reported in the console after device linking, but they are spurious because we retry a few times until we are successful. The change here removes the thrown exceptions until the last attempt.
To test the change:
1. Clone [Webnative app template](https://github.com/webnative-examples/webnative-app-template/tree/icidasset/webnative-0.35) and update Webnative to use `bgins/fix-did-root-exceptions`
2. Register a new user
3. Link the user's account on a new device
4. No uncaught exceptions should be reported, but warnings may be displayed on failed attempts
Fixes #430
=> Fix "Could not locate user DID in DNS" uncaught exceptions in device linking

src/session.ts
Small change to make the session's components private so that the session class instance is less confusing.
=> Make session components private

src/components/auth/channel.ts
During device linking, we lookup the root DID for a username. We should retry the lookup a few times, but an early `clearInterval` was stopping retries after the second attempt.
This PR also increases the number of attempts and their frequency to make this lookup more robust.
Go through the account linking flow with an existing user.
Go through it a second time with a non-existent user. The console should report ten warnings before throwing an exception and giving up.
Closes #446
=> Fix `waitForRootDid` retry issues

CHANGELOG.md
* Add `waitForRootDid` retry issues changelog entry
We pushed this fix into the `0.35.1` release so this PR adds a changelog entry for it.
=> Add missing `waitForRootDid` changelog entry

README.md
This provides general information about migrations and links to the migration section in the Fission guide.
Closes #453
=> Add migration section to guide

.github/workflows/docs.yaml
This will cause the docs site to update whenever a "stable" Github release is created. I first had the idea to do `releases/*` branches to trigger the docs but that was never done, and instead triggered the action manually.
=> Use better trigger for docs Github action

CHANGELOG.md, README.md, src/filesystem.ts, src/fs/types/params.ts, src/index.ts
Moving the FileSystem recovery functionality into `webnative`. Devs can now call the `recoverFileSystem` shorthand method directly from the `program`. It is important to note the `newUsername` and `oldUsername` that are passed in are the hashed versions, as `webnative` doesn't yet have a notion of the unhashed versions. (That will be completed in https://github.com/fission-codes/webnative/issues/385)
```ts
const { success } = await $sessionStore.program.recoverFileSystem({
newUsername,
oldUsername,
readKey
})
```
~~**Note: I'm not sure if we currently have the infrastructure in the codebase for this, but it would be cool if we could emit events at various parts of the recovery flow to update the message on the client 🤔**~~ Answered …
=> Avivash/File System Recovery Shorthand Method

CHANGELOG.md, src/index.ts, tests/helpers/filesystem.ts, tests/index.node.test.ts
Closes #443
```ts
program.accountDID(username)
```
I thought about doing just `program.accountDID()` without the username param which would depend on the session underneath and return `null` if not authed. But seeing that `loadFileSystem` also takes the `username` parameter, it makes sense to implement it that way.
=> Add shorthand accountDID method

CHANGELOG.md, README.md, src/fs/filesystem.ts, src/fs/types.ts
Matches the interface of rs-wnfs.
Closes #440 
Guide will need updating:
https://guide.fission.codes/developers/webnative/file-system-wnfs
=> Remove fs.add and fs.cat

CHANGELOG.md, src/capabilities.ts, src/common/identifiers.ts, src/common/root-key.ts, src/filesystem.ts, src/fs/bare/tree.ts, src/fs/base/tree.ts, src/fs/data.ts, src/fs/filesystem.ts, src/fs/root/tree.ts, src/fs/share.ts, src/fs/types.ts, src/fs/v1/PrivateTree.ts, src/fs/v1/PublicTree.ts, src/fs/v3/PublicRootWasm.ts, src/path/index.node.test.ts, src/path/index.ts, src/permissions.ts, src/repositories/ucans.ts, tests/fs/concurrency.node.test.ts, tests/fs/data.node.test.ts, tests/fs/integration.node.test.ts, tests/fs/share.node.test.ts, tests/fs/tree.node.test.ts, tests/helpers/filesystem.ts
This restricts the paths that can be used with the file system POSIX interface. For example, `fs.write` now requires a file path that starts with `"private"` or `"public"` and must have at least one more path segment.
```ts
fs.write(
path.file("private", "fileName")
)
```
The other neat thing about this is when you start writing the following in your editor with the Typescript LSP:
```ts
await fs.write(
Path.file("")
)
```
It'll suggest `"private"` or `"public"` so people don't have to guess anymore what to type in there as the first item.
- `Branch` has been renamed to `RootBranch`
- Introduces the concept of `Partition`s which are `RootBranch`es that can be used the POSIX file system interface.
- You can also use the `RootBranch` enum to provide string values, for the people that prefer …
=> Use stricter types for path creation

CHANGELOG.md, src/fs/v1/PrivateFile.ts, src/fs/v1/PrivateHistory.ts, src/fs/v1/PrivateTree.ts, src/fs/v1/PublicFile.ts, src/fs/v1/PublicHistory.ts, src/fs/v1/PublicTree.ts
Fixes #471 history retrieval.
Didn't catch this in the refactor because I used an `as unknown` before.
I replaced this with better types.
=> Fixes #471

CHANGELOG.md, package-lock.json, package.json, src/common/event-emitter.ts, src/components/auth/implementation.ts, src/components/auth/implementation/wnfs.ts, src/events.ts, src/filesystem.ts, src/fs/filesystem.ts, src/index.ts, tests/auth/linking.node.test.ts, tests/helpers/filesystem.ts
__Adds event emitters to the program.__ This allows you to say:
```ts
program.fileSystem.on("local-change", ({ path, root }) => {
console.log("The file system has changed locally 🔔")
console.log("Changed path:", path)
console.log("New data root CID:", root)
})
```
Events added so far
- `fileSystem["local-change"]`
- `fileSystem["published"]`
Events are documented automatically using the types:
#136
#413 
#414 
I'm not sure these issues can be closed since they may involve remote changes, which this PR does **not** include. Server changes are needed in order to achieve this. Personally I'd also like to wait for #163 before we go down that road. In any case, this is a good start and people can set up their own notification system using this.
=> Add event emitter interface and two file system events

CHANGELOG.md, README.md, src/configuration.ts, src/index.ts
Closes #405 
```ts
wn.program({
namespace: "example",
debug: true
})
const program = globalThis.__webnative.programs["example"]
```
Added a section to the [📜 README](https://github.com/fission-codes/webnative/tree/icidasset/debug-inject#debugging) that explains it.
=> Inject debug programs in globalThis context

CHANGELOG.md, src/fs/filesystem.ts
Fixes #480
We forgot to mark `mv` as a mutation 🙈
=> `fs.mv` is a mutation

CHANGELOG.md, src/events.ts, src/fs/filesystem.ts
=> Rename 'published' event to 'publish'

CHANGELOG.md, package-lock.json, package.json, src/common/version.ts, src/filesystem.ts, src/repositories/cid-log.node.test.ts
Testing the various states:
- **No data cid**: Create new account.
- **Up to date**: Refresh the page after a publish has successfully completed.
- **Outdated**: Refresh the page just after making a change in the file system and just before the publish has finished. That way the DNS becomes out of sync with your local state. Refreshing the page should say "outdated, 1 newer local entry". Repeating this process should increase this counter (ie. 2 newer local entries, and so on).
- **Newer**: Make a change in one session, wait for publish to finish and open app in other session.
Fixes #486 
You can test this with the alpha version: `0.36.1-alpha-1`
=> Fixes #486

src/fs/v3/PublicRootWasm.ts, tests/fs/wasm/public.test.ts
Fixes #429 
I added the "no changelog" label since this is only a fix for a feature behind an experimental feature flag. I don't think this needs a changelog entry. Right?
=> Fix & re-enable rs-wnfs integration tests

CHANGELOG.md, package-lock.json, package.json, src/common/cid.node.test.ts, src/common/cid.ts, src/common/version.ts
Should fix issues such as #459 where CIDs in the format of `{"/":"CID_STRING"}` (DAG-JSON) are encountered.
=> Parse DAG-JSON CIDs

CODE_OF_CONDUCT.md, CONTRIBUTING.md
This PR implements the following features:
This PR adds a contributing guide and code of conduct to set expectations around contributing and conduct in our project.
Closes #511
=> Add contributing guide

README.md
I noticed the link to `wnfs` in the README returns a 404 page.
=> fix a link in readme

CHANGELOG.md, package-lock.json, package.json, src/common/version.ts, src/components/capabilities/implementation/fission-lobby.ts, src/index.ts, src/ucan/token.ts
Turns out it didn't work after all when changing the message passed to `postMessage` 🙈 Also got rid of the `via-postmessage` check which added support for the old lobby which has long been deprecated for a while, and improved the retry function which wasn't working well (actually ran the action 20 times even though initial one succeeded).
=> Fix issue with capabilities component
